### ISSUE TITLE
Update SWMM time series file format

### ISSUE THREAD

**Issue by jamaa** [bluemodel/BlueM.Wave#118]
The file format classes `SWMM_DAT_MASS` and `SWMM_DAT_TIME` are supposed to handle the "SWMM DAT interface format", which is not really documented in the [wiki](https://wiki.bluemodel.org/index.php/SWMM_file_formats#SWMM5_DAT_interface_format). 

Both classes don't support reading files, only exporting. 

They differ only in that one uses `TimeSeries.getKontiZRE2()` ("for mass-based time series") and the other one uses `TimeSeries.getKontiZRE3()` ("for time-based time series") for making the time series equidistant before export. (This is also the only place where these two methods are used.)

The exported format in both cases looks something like this:
```
01.21.1981 18:15 1.78
01.21.1981 18:20 1.78
01.21.1981 18:25 1.78
01.21.1981 18:30 1.78
01.21.1981 18:35 1.78
01.21.1981 18:40 1.78
01.21.1981 18:45 1.78
01.21.1981 18:50 1.78
01.21.1981 18:55 1.78
```
Note the lack of a header/title or any metadata.

I suggest removing these two classes / the SWMM DAT interface file format. You can achieve very similar functionality by using the [ChangeTimeStep](https://wiki.bluemodel.org/index.php/Wave:ChangeTimestep) analysis function and then exporting to CSV.

Do you agree, @SHeusch ? If you feel that we should keep it, then I suggest we do as follows:
- [x] Find documentation on the SWMM DAT interface format and add it to the wiki
- [x] Consolidate both classes into one and use the newer method `TimeSeries.ChangeTimestep()` for making the time series equidistant before export (difference between time-based and mass-based can be solved by specifiying interpretation). See also https://github.com/bluemodel/BlueM.Wave/issues/46#issuecomment-1138927779.
- [x] Add a method for reading the SWMM DAT interface format

**Comment by SHeusch** [comment]
This file type is called "Time Series File" in SWMM. It has no header. It is required to connect it to an object within SWMM using the Time Series Editor.  This is taken from the SWMM-documentary:
[SWMM_TimeSeriesFiles.pdf](https://github.com/bluemodel/BlueM.Wave/files/12753646/SWMM_TimeSeriesFiles.pdf)
Shall we use this for the wiki?
I have no objections consolidating both classes. A method for reading such files would be nice but it has no high priority...

**Comment by jamaa** [comment]
Aha, good to know! Ok we'll keep it as an export-only format, but I will rename it to "SWMM Time Series File". 

I saw that headers starting with `;` are allowed so I will add that to the export routine as well.

But after seeing the docs, I think I want to completely remove the automatic conversion to an equidistant timestep before export. I believe SWMM can work with any length between timesteps? If a user needs the file to be in a certain timestep , they can always use the ChangeTimeStep analysis function before exporting.

**Comment by jamaa** [comment]
> Shall we use this for the wiki?

I found the documentation at https://www.epa.gov/system/files/documents/2022-04/swmm-users-manual-version-5.2.pdf
I think its better to just copy the relevant parts to the wiki and link to the official PDF.

**Comment by SHeusch** [comment]
Yeah, I took the two pages from that documentary. I'll put it in the Wiki asap.

**Comment by SHeusch** [comment]
> But after seeing the docs, I think I want to completely remove the automatic conversion to an equidistant timestep before export. I believe SWMM can work with any length between timesteps? If a user needs the file to be in a certain timestep , they can always use the ChangeTimeStep analysis function before exporting.

That's fine with me.

**Comment by jamaa** [comment]
I'll update the wiki myself, give you more time for testing ;-)

**Comment by SHeusch** [comment]
I've played around with these files: the import of the example file from our own wiki doesn't work and looking into SWMM I don't see much value for that format. I suggest to delete the "SWMM Time Series Format" from SWMM.

**Comment by SHeusch** [comment]
We get rid of those unwanted classes as well.

**Comment by jamaa** [comment]
I added a commit 39866e66f620549cf7c4881d5234697cb72cb450 to the SWMM branch yesterday to handle the SWMM time series format. It should be working now, here's a test file I created from the example in the SWMM documentation: https://github.com/bluemodel/BlueM.Datasets/blob/master/Wave/SWMM/SWMM5_TimeSeriesFile.dat

**Comment by SHeusch** [comment]
OK, I will try the import and export of your example file later today.

**Comment by SHeusch** [comment]
Well done. I tested the import and export options, works well with SWMM. Thanks.
