### ISSUE TITLE
Plotting position and fitting of probability distributions

### ISSUE THREAD

**Issue by TobiasRosskopf** [bluemodel/BlueM.Wave#91]
Inspired by the existing analysis function AnnualStatistics it would be great to go steps further and analyse the annual maxima for recurrence probability. A first approach would be the implementation of plotting position (first try see below). After this we could try to add the possibility of fitting various probability distributions such as Gumbel, Pearson 3, Weibull, ...

![Wave_PlottingPositions](https://user-images.githubusercontent.com/42942019/210563102-809fb552-5c46-4392-9335-f759418fa4f7.png)

A good template could be the comercial standard software HQ-EX from DHI:

[HQ-EX 4.0 Flyer (PDF)](https://www.dhigroup.com/-/media/shared%20content/presences/emea/germany/flyers%20and%20pdf/solution/dhi_solution_hq-ex4,-d-,0_de_v2,-d-,0.pdf)
[HQ-EX 4.0 User Manual (PDF)](https://www.mikepoweredbydhi.com/download/-/media/00a6177b984c4388874b4e8fd37190ef.ashx)

![hqex](https://user-images.githubusercontent.com/42942019/210813672-48b20b1a-693c-4f44-9799-f7a5ef21726d.PNG)

**Comment by jamaa** [comment]
Yes, nice idea!

For fitting probability distributions, maybe the already inluded [Math.NET Numerics](https://numerics.mathdotnet.com/) library can help us. It already contains [a few distributions](https://numerics.mathdotnet.com/api/MathNet.Numerics.Distributions/) and also has a [Fit](https://numerics.mathdotnet.com/api/MathNet.Numerics/Fit.htm) method for non-linear least-squares fitting an arbitrary function with up to 5 parameters to a set of points.

**Comment by TobiasRosskopf** [comment]
Thanks, this is really good to know!

**Comment by jamaa** [comment]
@TobiasRosskopf I would like to integrate the Plotting Position feature into the master branch and include it in the next release, before the branch gets too old. We can always still add distribution functions later. Can you please make a pull request? Let me know if you don't have the time for it, and I will do it.
